// <auto-generated />
namespace ORCA30523.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class removeforiegnkeys2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeforiegnkeys2));
        
        string IMigrationMetadata.Id
        {
            get { return "201612050020567_removeforiegnkeys2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
