//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORCA30523.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string CommentID { get; set; }
        public string PostID { get; set; }
        public string Body { get; set; }
        public string Username { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string ApplicationUser_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Post Post { get; set; }
    }
}
